# Coleta de Dados — YouTube (Redpill/Manosfera)

Notebook orquestrador da coleta, dividido em 5 etapas que seguem a metodologia:

1. **Busca de vídeos por query** (top 50 por query, com paginação)
2. **Filtro por palavras-chave** (título/descrição) — local, sem custo de quota
3. **Detalhes de canais + filtro de canais com < 5 vídeos**
4. **Coleta de todos os vídeos de cada canal aprovado** (com paginação, excluindo Shorts)
5. **Coleta de top comentários + replies de cada vídeo**

### Como funciona o controle de quota e checkpoint
Cada etapa:
- Registra o custo de cada chamada no `QuotaManager`, que persiste o estado em `data/quota_state.json`.
- Salva o progresso incrementalmente em CSV (`data/*.csv`) e marca o que já foi processado em `data/*_progress.json`.
- **Pode ser interrompida e retomada a qualquer momento** (inclusive em outro dia) — basta rodar a célula de novo, ela vai pular o que já está pronto e continuar de onde parou.
- Se a quota diária estiver perto do limite, a etapa **para automaticamente** (com uma margem de segurança) antes de gerar erro 403 da API.

⚠️ **Antes de rodar**: preencha sua `API_KEY` na célula de configuração abaixo.

## 0. Setup

In [ ]:
# Se necessário, instale as dependências (rode uma vez):
# %pip install google-api-python-client pandas

In [1]:
import sys
sys.path.insert(0, "src")  # módulos do projeto

import ast
import pandas as pd
from googleapiclient.discovery import build

from quota_manager import QuotaManager, QuotaExceededError
from checkpoint import ProgressTracker, append_rows_csv, load_csv_or_empty
from search_video_by_query import search_videos
from get_video_details import get_videos_details
from keyword_filter import filter_videos_by_keywords
from search_channels_details import search_channels
from search_videos_from_channel import search_videos_from_channel
from get_top_comments import get_top_comments, CommentsDisabledError
from get_replies import get_all_replies

In [2]:
# ⚠️ PREENCHA SUA CHAVE DE API AQUI
API_KEY = "AIzaSyA7la3zxS0gcbk_8b9iyxGYNEK6qJTXPS0"
youtube = build("youtube", "v3", developerKey=API_KEY)

# Quota diária do seu projeto no Google Cloud (padrão free tier = 10000)
DAILY_QUOTA_LIMIT = 10000
SAFETY_MARGIN = 200  # unidades reservadas que nunca serão gastas (evita passar do limite)

quota = QuotaManager(daily_limit=DAILY_QUOTA_LIMIT, safety_margin=SAFETY_MARGIN,
                      state_file="data/quota_state.json")
quota.print_status()

📊 Quota [2026-06-20]: 0/10000 usadas (margem de segurança: 200) -> restante hoje (seguro): 9800

In [3]:
# Carrega as palavras-chave e queries do arquivo de texto
with open("data/Palavras-Chave_e_Queries_usadas_para_Coleta.txt", "r", encoding="utf-8") as f:
    conteudo = f.read()

data_kw = ast.literal_eval("{" + conteudo + "}")
key_words = data_kw["key_words"]
queries = data_kw["queries"]

print(f"Queries carregadas: {len(queries)}")
print(f"Palavras-chave carregadas: {len(key_words)}")

Queries carregadas: 66
Palavras-chave carregadas: 139

## Etapa 1 — Busca de vídeos por query (top 50 cada)

Custo: **100 unidades por query** (1 página de até 50 resultados).
Com paginação: se algum dia você quiser aumentar o `max_results` por query
para mais de 50, a função já pagina automaticamente.

Checkpoint: `data/videos_raw.csv` + `data/etapa1_progress.json` (queries já buscadas).
Pode ser interrompida e retomada — queries já buscadas não são refeitas.

In [4]:
progress_etapa1 = ProgressTracker("data/etapa1_progress.json")
queries_pendentes = progress_etapa1.pending(queries)

print(f"Queries já processadas: {len(progress_etapa1)}/{len(queries)}")
print(f"Queries pendentes nesta execução: {len(queries_pendentes)}")

for query in queries_pendentes:
    print(f"🔎 Buscando: {query}")
    resultados, completo = search_videos(query, youtube, quota_manager=quota, max_results=50)

    if resultados:
        append_rows_csv("data/videos_raw.csv", resultados, dedup_cols=["query", "id_video"])

    if completo:
        progress_etapa1.mark_done(query)
    else:
        print(f"\n⏸️  Quota insuficiente para terminar a query '{query}'. "
              f"O que foi coletado até agora ficou salvo; a query será retomada "
              f"(refeita do início) na próxima execução. Pausando Etapa 1.")
        break

quota.print_status()

Queries já processadas: 0/66
Queries pendentes nesta execução: 66
🔎 Buscando: O que é Red Pill?
🔎 Buscando: O que significa VSM?
🔎 Buscando: O que é Valor Sexual de Mercado?
🔎 Buscando: O que significa Hipergamia?
🔎 Buscando: Homem Alfa vs Homem Beta
🔎 Buscando: Mulher 304, o que significa?
🔎 Buscando: O que é Monkey Branching?
🔎 Buscando: A teoria 80/20 na Redpill
🔎 Buscando: Chad vs Beta: diferenças
🔎 Buscando: O que significa "Femimimi"?
🔎 Buscando: Polo Masculino e Polo Feminino: qual a diferença?
🔎 Buscando: Como aumentar o VSM?
🔎 Buscando: A verdade sobre a hipergamia feminina
🔎 Buscando: Por que o homem deve ser Alfa?
🔎 Buscando: Como aumentar meu valor sexual de mercado?
🔎 Buscando: Qual a mulher ideal para um homem de valor?
🔎 Buscando: Como ser um homem de valor?
🔎 Buscando: Quando as mulheres chegam na The Wall, o que fazer?
🔎 Buscando: Como encontrar uma mulher ideal?
🔎 Buscando: Incel vs Red Pill
🔎 Buscando: Feminista vs Red Pill
🔎 Buscando: Por que o feminismo é ruim?
🔎 Buscando: Como ser um bom Red Pill?
🔎 Buscando: Como encontrar a verdade da Red Pill?
🔎 Buscando: O que é a machosfera?
🔎 Buscando: Quem faz parte da manosfera?
🔎 Buscando: O que é uma mulh3re 304?
🔎 Buscando: O que significa miqueinha na Redpill?
🔎 Buscando: O que é uma bostileira?
🔎 Buscando: A coomecracia existe mesmo?
🔎 Buscando: O que é coomer?
🔎 Buscando: Looksmaxxing funciona?
🔎 Buscando: Qual o papel do homem na sociedade Redpill?
🔎 Buscando: AWALT: todas as mulheres são iguais?
🔎 Buscando: Por que o homem moderno sofre?
🔎 Buscando: Existe solução para o homem Beta?
🔎 Buscando: Como escapar da coomecracia?
🔎 Buscando: A verdade por trás da The Wall
🔎 Buscando: Por que ser um Alfa Sigma é importante?
🔎 Buscando: Blackpill vs Redpill: diferenças
🔎 Buscando: Como funciona o SMV masculino?
🔎 Buscando: Por que as mulheres preferem o 20% dos homens?
🔎 Buscando: Qual a crítica da Redpill ao feminismo?
🔎 Buscando: Como atingir o auge do valor masculino?
🔎 Buscando: como usar bem a mask pill
🔎 Buscando: ser alfa
🔎 Buscando: sou beta?
🔎 Buscando: como virar alfa
🔎 Buscando: o que é vsm
🔎 Buscando: mulher na wall
🔎 Buscando: valor masculino
🔎 Buscando: como virar chad
🔎 Buscando: qual é meu valor no mercado sexual
🔎 Buscando: diferença entre chad e beta
🔎 Buscando: hipergamia é real?
🔎 Buscando: todas as mulheres são iguais?
🔎 Buscando: como funciona a redpill
🔎 Buscando: como ser redpillado
🔎 Buscando: o que é o movimento redpill
🔎 Buscando: o que significa 304?
🔎 Buscando: o que é coomecracia?
🔎 Buscando: por que os homens sofrem?
🔎 Buscando: como escapar da matrix?
🔎 Buscando: como pensar como redpill
🔎 Buscando: me tornei redpill
🔎 Buscando: por que devemos usar mask pill
📊 Quota [2026-06-18]: 6600/10000 usadas (margem de segurança: 200) -> restante hoje (seguro): 3200

In [5]:
df_videos_raw = load_csv_or_empty("data/videos_raw.csv")
print(f"Total de linhas (query, vídeo) coletadas até agora: {len(df_videos_raw)}")
print(f"Vídeos únicos: {df_videos_raw['id_video'].nunique() if len(df_videos_raw) else 0}")
df_videos_raw.head()

Total de linhas (query, vídeo) coletadas até agora: 3018
Vídeos únicos: 2547

,query,id_video,title,description_snippet,channelId,published_at
0,O que é Red Pill?,HRoqCGqFVkA,O que é o movimento redpill e por que tanta ge...,Seja membro deste canal e ganhe benefícios: ht...,UC5VvsTwsyKWMZSQtt1MPCEw,2025-07-22T22:00:15Z
1,O que é Red Pill?,dvLdZzwPviY,Neurocientista perdeu a linha ao falar sobre R...,NaN,UC85ZBc5dtx-PhUUyTX31ZQg,2025-06-06T15:01:19Z
2,O que é Red Pill?,udT14C1nE_w,"Redpill, o Movimento Mais Perigoso da Internet","Tenha Bitcoin na sua vida e ganhe R$25,00: htt...",UC2IfVRihAWEHuZS56unh3uw,2025-09-15T16:35:46Z
3,O que é Red Pill?,Ct-FYd6K7cE,CONHEÇA AGORA o GLOSSÁRIO COMPLETO RED PILL,DRA. SOLANGE BERETTA é ex-promotora de justiça...,UCvmWNQH4c2T3Triih3lftiw,2025-04-03T16:04:33Z
4,O que é Red Pill?,VGL8iuZsJtw,PROJETO CHAD: O Redpill mais Patético da Internet,Instagram: @irlNeonㅤ Twitter: @neon_irl Email ...,UClqQr4H1HadkCaK_ZrlmQ2Q,2024-04-22T22:42:46Z

## Etapa 1b — Detalhes completos dos vídeos (descrição + duração)

O `search.list` não traz a descrição completa nem a duração do vídeo.
Como o filtro de palavras-chave precisa olhar a descrição completa, e a
exclusão de Shorts (etapa 4) precisa da duração, buscamos os detalhes
completos aqui via `videos.list` (muito mais barato: **1 unidade por lote
de até 50 vídeos**, em vez de pagar de novo o custo de busca).

Checkpoint: `data/videos_details.csv` + `data/etapa1b_progress.json` (video_ids já detalhados).

In [6]:
progress_etapa1b = ProgressTracker("data/etapa1b_progress.json")

video_ids_unicos = df_videos_raw["id_video"].dropna().unique().tolist()
video_ids_pendentes = progress_etapa1b.pending(video_ids_unicos)

print(f"Vídeos únicos totais: {len(video_ids_unicos)}")
print(f"Pendentes de detalhamento: {len(video_ids_pendentes)}")

LOTE = 50

for i in range(0, len(video_ids_pendentes), LOTE):
    lote_ids = video_ids_pendentes[i:i + LOTE]
    detalhes, completo = get_videos_details(lote_ids, youtube, quota_manager=quota)

    if detalhes:
        append_rows_csv("data/videos_details.csv", list(detalhes.values()), dedup_col="video_id")
        # Marca apenas os IDs que de fato vieram na resposta
        progress_etapa1b.mark_many_done(list(detalhes.keys()))

    if not completo:
        print(f"\n⏸️  Quota insuficiente. Pausando Etapa 1b.")
        break

quota.print_status()

Vídeos únicos totais: 2547
Pendentes de detalhamento: 2547
📊 Quota [2026-06-18]: 6651/10000 usadas (margem de segurança: 200) -> restante hoje (seguro): 3149

In [7]:
df_videos_details = load_csv_or_empty("data/videos_details.csv")
print(f"Vídeos com detalhes coletados: {len(df_videos_details)}")
df_videos_details.head()

Vídeos com detalhes coletados: 2547

,video_id,title,description,channelId,published_at,duration_iso,duration_seconds,is_short,view_count,like_count,comment_count
0,HRoqCGqFVkA,O que é o movimento redpill e por que tanta ge...,Seja membro deste canal e ganhe benefícios:\nh...,UC5VvsTwsyKWMZSQtt1MPCEw,2025-07-22T22:00:15Z,PT8M17S,497,False,274205,9269.0,1999.0
1,dvLdZzwPviY,Neurocientista perdeu a linha ao falar sobre R...,NaN,UC85ZBc5dtx-PhUUyTX31ZQg,2025-06-06T15:01:19Z,PT44S,44,True,66931,2672.0,564.0
2,udT14C1nE_w,"Redpill, o Movimento Mais Perigoso da Internet","💵 Tenha Bitcoin na sua vida e ganhe R$25,00: h...",UC2IfVRihAWEHuZS56unh3uw,2025-09-15T16:35:46Z,PT30M58S,1858,False,179622,19824.0,2436.0
3,Ct-FYd6K7cE,CONHEÇA AGORA o GLOSSÁRIO COMPLETO RED PILL,DRA. SOLANGE BERETTA é ex-promotora de justiça...,UCvmWNQH4c2T3Triih3lftiw,2025-04-03T16:04:33Z,PT12M22S,742,False,28316,1407.0,500.0
4,VGL8iuZsJtw,PROJETO CHAD: O Redpill mais Patético da Internet,📷 Instagram: @irlNeonㅤ\n🐦 Twitter: @neon_irl\n...,UClqQr4H1HadkCaK_ZrlmQ2Q,2024-04-22T22:42:46Z,PT15M39S,939,False,575949,38739.0,1700.0

## Etapa 2 — Filtro por palavras-chave (título OU descrição)

Esta etapa é **100% local** (sem custo de quota). Mantém apenas vídeos
cujo título ou descrição contenha pelo menos uma das palavras-chave da
lista pré-definida (comparação *case-insensitive*).

In [13]:
videos_para_filtrar = df_videos_details.to_dict("records")

aprovados, reprovados = filter_videos_by_keywords(
    videos_para_filtrar, key_words,
    title_field="title", description_field="description"
)

print(f"Vídeos aprovados (contêm keyword): {len(aprovados)}")
print(f"Vídeos reprovados (descartados): {len(reprovados)}")

df_videos_aprovados = pd.DataFrame(aprovados)
df_videos_aprovados.to_csv("data/videos_aprovados_keywords.csv", index=False)
df_videos_aprovados.head()

Vídeos aprovados (contêm keyword): 1082
Vídeos reprovados (descartados): 1465

,video_id,title,description,channelId,published_at,duration_iso,duration_seconds,is_short,view_count,like_count,comment_count
0,HRoqCGqFVkA,O que é o movimento redpill e por que tanta ge...,Seja membro deste canal e ganhe benefícios:\nh...,UC5VvsTwsyKWMZSQtt1MPCEw,2025-07-22T22:00:15Z,PT8M17S,497,False,274205,9269.0,1999.0
1,dvLdZzwPviY,Neurocientista perdeu a linha ao falar sobre R...,NaN,UC85ZBc5dtx-PhUUyTX31ZQg,2025-06-06T15:01:19Z,PT44S,44,True,66931,2672.0,564.0
2,udT14C1nE_w,"Redpill, o Movimento Mais Perigoso da Internet","💵 Tenha Bitcoin na sua vida e ganhe R$25,00: h...",UC2IfVRihAWEHuZS56unh3uw,2025-09-15T16:35:46Z,PT30M58S,1858,False,179622,19824.0,2436.0
3,Ct-FYd6K7cE,CONHEÇA AGORA o GLOSSÁRIO COMPLETO RED PILL,DRA. SOLANGE BERETTA é ex-promotora de justiça...,UCvmWNQH4c2T3Triih3lftiw,2025-04-03T16:04:33Z,PT12M22S,742,False,28316,1407.0,500.0
4,VGL8iuZsJtw,PROJETO CHAD: O Redpill mais Patético da Internet,📷 Instagram: @irlNeonㅤ\n🐦 Twitter: @neon_irl\n...,UClqQr4H1HadkCaK_ZrlmQ2Q,2024-04-22T22:42:46Z,PT15M39S,939,False,575949,38739.0,1700.0

## Etapa 3 — Detalhes de canais + filtro de relevância

Busca detalhes dos canais e aplica **dois filtros em sequência**:

1. **Mínimo de vídeos** (`video_count >= MIN_VIDEOS_CANAL`): remove canais muito pequenos.
2. **Relevância temática** (`relevance_score >= MIN_RELEVANCE_SCORE`): remove canais onde o tema aparece só de passagem. O `relevance_score` é a razão entre o número de vídeos do canal que apareceram nas queries e o `video_count` total do canal. Um canal com 1.000 vídeos onde apenas 2 apareceram nas queries tem score 0,002 — provavelmente não é um canal focado no tema.

**Novos campos retornados:**
- `topic_categories`: categorias legíveis do canal (ex: `Society`, `Entertainment`, `Music`) extraídas do campo `topicDetails.topicCategories` da API.
- `channel_keywords`: tags livres definidas pelo próprio criador do canal.
- `relevance_score`: proxy de foco temático (vídeos encontrados nas queries / total de vídeos).

Custo: **1 unidade por lote de até 50 canais** — inalterado, pois os `parts` extras (`topicDetails`, `brandingSettings`) não aumentam o custo de quota.

In [4]:
df_videos_aprovados = load_csv_or_empty("data/videos_aprovados_keywords.csv")

In [5]:
canais_unicos = df_videos_aprovados["channelId"].dropna().unique().tolist()
print(f"Canais únicos a verificar: {len(canais_unicos)}")

# Conta quantos vídeos de cada canal apareceram nas queries (usado para calcular relevance_score)
videos_por_canal = (
    df_videos_aprovados.groupby("channelId")["video_id"]
    .nunique()
    .to_dict()
)

detalhes_canais, completo = search_channels(
    canais_unicos, youtube,
    quota_manager=quota,
    videos_por_canal=videos_por_canal,
)

if not completo:
    print("⏸️  Quota insuficiente para detalhar todos os canais. "
          "Os que já vieram estão salvos. Rode novamente para continuar.")

df_canais = pd.DataFrame(list(detalhes_canais.values()))
df_canais.to_csv("data/canais_detalhes.csv", index=False, sep = ";")

quota.print_status()
df_canais[["channelId","channel_title","video_count","subscribers",
           "topic_categories_str","relevance_score"]].head(10)

Canais únicos a verificar: 739

TimeoutError: [WinError 10060] Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu

In [7]:
MIN_VIDEOS_CANAL = 5
MIN_RELEVANCE_SCORE = 0.002

df_canais_aprovados = df_canais[(df_canais["video_count"] >= MIN_VIDEOS_CANAL) & (df_canais['relevance_score']>MIN_RELEVANCE_SCORE)].copy()
df_canais_aprovados.to_csv("data/canais_aprovados.csv", index=False)

print(f"Canais com >= {MIN_VIDEOS_CANAL} vídeos (aprovados): {len(df_canais_aprovados)}")
print(f"Canais descartados (< {MIN_VIDEOS_CANAL} vídeos): {len(df_canais) - len(df_canais_aprovados)}")
df_canais_aprovados.head()

Canais com >= 5 vídeos (aprovados): 453
Canais descartados (< 5 vídeos): 286

,channelId,channel_title,country,subscribers,video_count,view_count,topic_categories,topic_categories_str,channel_keywords,videos_found_in_queries,relevance_score
0,UC9hWb5udOw3D6di5bKeWMYw,viniciusinthernet,BR,576000,154,95174512,"[Entertainment, Humour, Lifestyle (sociology)]",Entertainment | Humour | Lifestyle (sociology),viniciusinthernet,1,0.0065
1,UCaKEqmX7HJGIf75b4VJVGDA,Renata Ellera Gomes,NaN,792,88,101651,"[Knowledge, Lifestyle (sociology)]",Knowledge | Lifestyle (sociology),NaN,1,0.0114
2,UCSpUAJw93VIHVn8k-JP8NTQ,Sedutor Afro (Gabriel Amorim),BR,118000,810,12821599,"[Health, Lifestyle (sociology)]",Health | Lifestyle (sociology),"relacionamentos ""desenvolvimento masculino"" ""d...",7,0.0086
4,UC3aZ_QhGp7zUiUctPF9lw9g,2pCast Oficial,BR,8300,265,1044536,"[Society, Lifestyle (sociology), Knowledge]",Society | Lifestyle (sociology) | Knowledge,"comunicação ""comunicação assertiva"" ""futuro do...",1,0.0038
5,UC6wAyZ8dgsaJgaReKDwtf5Q,No Fugazee Clips,US,16400,138,6255710,[Society],Society,#Dating #Men #Women #redpill #Feminism #Femini...,1,0.0072

## Etapa 4 — Coletar todos os vídeos de cada canal aprovado

Para cada canal aprovado, busca **todos** os vídeos publicados (com
paginação completa — diferente do código original, que só pegava a
primeira página). Em seguida, usa `videos.list` para descobrir a duração
de cada vídeo e **excluir Shorts** (duração ≤ 60s), conforme decidido.

⚠️ Esta é a etapa mais cara em quota (cada página de 50 vídeos custa
100 unidades). Para canais muito grandes, a coleta pode levar vários dias
— é exatamente para isso que o checkpoint por canal existe: cada canal só
é marcado como concluído quando **todos** os seus vídeos foram coletados.

Checkpoint: `data/canal_videos_raw.csv` + `data/etapa4_progress.json` (canais já 100% coletados).

In [8]:
progress_etapa4 = ProgressTracker("data/etapa4_progress.json")

canais_pendentes = progress_etapa4.pending(df_canais_aprovados["channelId"].tolist())
print(f"Canais já 100% coletados: {len(progress_etapa4)}")
print(f"Canais pendentes nesta execução: {len(canais_pendentes)}")

for channel_id in canais_pendentes:
    print(f"📺 Coletando vídeos do canal {channel_id}...")
    videos_canal, completo = search_videos_from_channel(channel_id, youtube, quota_manager=quota)

    if videos_canal:
        append_rows_csv("data/canal_videos_raw.csv", videos_canal, dedup_col="id_video")

    if completo:
        progress_etapa4.mark_done(channel_id)
    else:
        print(f"\n⏸️  Quota insuficiente para terminar o canal {channel_id} "
              f"(canal grande, requer várias páginas). O que já foi coletado ficou salvo; "
              f"este canal será refeito do início na próxima execução "
              f"(os vídeos repetidos são automaticamente deduplicados). Pausando Etapa 4.")
        break

quota.print_status()

Canais já 100% coletados: 0
Canais pendentes nesta execução: 453
📺 Coletando vídeos do canal UC9hWb5udOw3D6di5bKeWMYw...
📺 Coletando vídeos do canal UCaKEqmX7HJGIf75b4VJVGDA...
📺 Coletando vídeos do canal UCSpUAJw93VIHVn8k-JP8NTQ...
📺 Coletando vídeos do canal UC3aZ_QhGp7zUiUctPF9lw9g...

PermissionError: [Errno 13] Permission denied: 'data/quota_state.json'

In [ ]:
df_canal_videos_raw = load_csv_or_empty("data/canal_videos_raw.csv")
print(f"Total de vídeos coletados dos canais até agora: {len(df_canal_videos_raw)}")
df_canal_videos_raw.head()

### Etapa 4b — Detalhar duração e excluir Shorts

Reaproveita o mesmo módulo `get_videos_details` (1 unidade por lote de 50)
para descobrir a duração de cada vídeo coletado e remover os Shorts
(duração ≤ 60 segundos).

In [ ]:
progress_etapa4b = ProgressTracker("data/etapa4b_progress.json")

ids_canal_videos = df_canal_videos_raw["id_video"].dropna().unique().tolist()
ids_pendentes_4b = progress_etapa4b.pending(ids_canal_videos)

print(f"Vídeos de canais pendentes de detalhamento: {len(ids_pendentes_4b)}")

LOTE = 50
for i in range(0, len(ids_pendentes_4b), LOTE):
    lote_ids = ids_pendentes_4b[i:i + LOTE]
    detalhes, completo = get_videos_details(lote_ids, youtube, quota_manager=quota)

    if detalhes:
        append_rows_csv("data/canal_videos_details.csv", list(detalhes.values()), dedup_col="video_id")
        progress_etapa4b.mark_many_done(list(detalhes.keys()))

    if not completo:
        print("\n⏸️  Quota insuficiente. Pausando Etapa 4b.")
        break

quota.print_status()

In [ ]:
df_canal_videos_details = load_csv_or_empty("data/canal_videos_details.csv")

df_canal_videos_finais = df_canal_videos_details[df_canal_videos_details["is_short"] == False].copy()
df_canal_videos_finais.to_csv("data/canal_videos_finais.csv", index=False)

print(f"Vídeos detalhados: {len(df_canal_videos_details)}")
print(f"Vídeos após excluir Shorts: {len(df_canal_videos_finais)}")
df_canal_videos_finais.head()

## Etapa 5 — Top comentários + replies de cada vídeo

Para cada vídeo final (Etapa 4b), busca os **top 50 comentários** e, para
cada comentário com `reply_count > 0`, busca até **20 replies**.

Custo aproximado por vídeo:
- `commentThreads.list`: **1 unidade** (50 resultados cabem em 1 página)
- `comments.list` (replies): **1 unidade por comentário-pai com replies**
  (a maior parcela do custo total da coleta inteira)

Checkpoint: vídeos já processados (comentários + replies) são marcados em
`data/etapa5_progress.json` e nunca reprocessados. Comentários desativados
também são marcados como "concluídos" (não há o que coletar).

In [ ]:
progress_etapa5 = ProgressTracker("data/etapa5_progress.json")

videos_para_comentarios = df_canal_videos_finais["video_id"].dropna().unique().tolist()
videos_pendentes_5 = progress_etapa5.pending(videos_para_comentarios)

print(f"Vídeos já processados (comentários): {len(progress_etapa5)}")
print(f"Vídeos pendentes nesta execução: {len(videos_pendentes_5)}")

MAX_COMMENTS = 50
MAX_REPLIES = 20

for video_id in videos_pendentes_5:
    try:
        top_comments, comments_completo = get_top_comments(
            video_id, youtube, quota_manager=quota, max_comments=MAX_COMMENTS
        )
    except CommentsDisabledError:
        progress_etapa5.mark_done(video_id)  # nada a coletar, não tentar de novo
        continue

    if top_comments:
        append_rows_csv("data/top_comments.csv", top_comments, dedup_col="comment_id")

    if not comments_completo:
        print(f"\n⏸️  Quota insuficiente para terminar os comentários do vídeo {video_id}. "
              f"Pausando Etapa 5 (vídeo será retomado na próxima execução).")
        break

    # Busca replies apenas dos comentários que de fato têm reply_count > 0.
    # Se a quota acabar no meio das replies, o vídeo NÃO é marcado como concluído:
    # na próxima execução ele refaz get_top_comments (idempotente, já filtra
    # duplicatas via dedup_col) e tenta as replies de novo.
    video_terminou_sem_interrupcao = True
    for c in top_comments:
        replies, replies_completo = get_all_replies(
            c["comment_id"], video_id, youtube,
            quota_manager=quota, max_replies=MAX_REPLIES,
            known_reply_count=c.get("reply_count"),
        )
        if replies:
            append_rows_csv("data/replies.csv", replies, dedup_col="comment_id")

        if not replies_completo:
            print(f"\n⏸️  Quota insuficiente no meio das replies do vídeo {video_id}. "
                  f"Pausando Etapa 5 (o vídeo será retomado na próxima execução).")
            video_terminou_sem_interrupcao = False
            break

    if video_terminou_sem_interrupcao:
        progress_etapa5.mark_done(video_id)
    else:
        break

quota.print_status()

In [ ]:
df_top_comments = load_csv_or_empty("data/top_comments.csv")
df_replies = load_csv_or_empty("data/replies.csv")

print(f"Top comentários coletados: {len(df_top_comments)}")
print(f"Replies coletadas: {len(df_replies)}")
df_top_comments.head()

## Status geral da coleta

Resumo de progresso de cada etapa e da quota consumida — útil para rodar
a qualquer momento e ver "quanto falta".

In [ ]:
# Esta célula pode ser rodada independentemente, sem precisar ter rodado
# as outras etapas na mesma sessão do kernel.

import ast

with open("data/Palavras-Chave_e_Queries_usadas_para_Coleta.txt", "r", encoding="utf-8") as f:
    _data_kw = ast.literal_eval("{" + f.read() + "}")

_queries = _data_kw["queries"]

_pt1  = ProgressTracker("data/etapa1_progress.json")
_pt1b = ProgressTracker("data/etapa1b_progress.json")
_pt4  = ProgressTracker("data/etapa4_progress.json")
_pt4b = ProgressTracker("data/etapa4b_progress.json")
_pt5  = ProgressTracker("data/etapa5_progress.json")

_df_canais_ap = load_csv_or_empty("data/canais_aprovados.csv")
_df_finais    = load_csv_or_empty("data/canal_videos_finais.csv")

def _resumo(nome, total, feitos):
    pct = (feitos / total * 100) if total else 0
    barra = "█" * int(pct // 5) + "░" * (20 - int(pct // 5))
    print(f"  [{barra}] {pct:5.1f}%  {nome}: {feitos}/{total}")

print("=" * 60)
print("  PROGRESSO DA COLETA")
print("=" * 60)
_resumo("Etapa 1  — Queries buscadas",         len(_queries),                   len(_pt1))
_resumo("Etapa 1b — Vídeos detalhados (raw)",  load_csv_or_empty("data/videos_raw.csv")["id_video"].nunique() if len(load_csv_or_empty("data/videos_raw.csv")) else 0, len(_pt1b))
_resumo("Etapa 4  — Canais 100% coletados",    len(_df_canais_ap),               len(_pt4))
_resumo("Etapa 4b — Vídeos de canal detalhados", len(load_csv_or_empty("data/canal_videos_raw.csv")), len(_pt4b))
_resumo("Etapa 5  — Vídeos com comentários",   len(_df_finais["video_id"].dropna().unique()) if len(_df_finais) else 0, len(_pt5))
print()
quota.print_status()
print()
_df_top = load_csv_or_empty("data/top_comments.csv")
_df_rep = load_csv_or_empty("data/replies.csv")
print(f"  Comentários coletados: {len(_df_top):,}")
print(f"  Replies coletadas:     {len(_df_rep):,}")